/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package farm_owner;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author PRO_
 */
public class Crops extends javax.swing.JFrame {

    /**
     * Creates new form Crops
     */
    public Crops() 
    {
        initComponents();
        Show_data_in_JTable();
    }
public Connection getConnection()
{
    Connection con;
    try
    {
        con=DriverManager.getConnection("jdbc:mysql://localhost/farm_owner", "root", "");
        return con;
    }
    catch(Exception e)
            {
                e.printStackTrace();
                return null;
            }
}
public ArrayList<Crop_main> getCrop_mainList()
{
    ArrayList<Crop_main> Crop_mainList= new ArrayList<Crop_main>();
    Connection connection= getConnection();
    String query= "Select * From crops";
    Statement st;
    ResultSet rs;
    try
    {
        st= connection.createStatement();
        rs= st.executeQuery(query);
        Crop_main crop_m;
        while(rs.next())
        {
            crop_m= new Crop_main(rs.getInt("Serial"),rs.getString("Product_Name"),rs.getString("Quantity"));
            Crop_mainList.add(crop_m);
        }
    }
    catch(Exception e)
    {
        e.printStackTrace();
    }
    return Crop_mainList;
}
//display data in JTable
   public void Show_data_in_JTable()
   {
       ArrayList<Crop_main> list= getCrop_mainList();
       DefaultTableModel model= (DefaultTableModel)jTable_crop.getModel();
       Object[] row= new Object[3];
       for(int i=0;i<list.size();i++)
       {
           row[0]= list.get(i).getSerial();
           row[1]= list.get(i).getProductName();
           row[2]= list.get(i).getQuantity();
           
           model.addRow(row);  
       }
   }
   //execute the sql query
   public void executeSQLQuery(String query, String message)
   {
       Connection con= getConnection();
       Statement st;
       try
       {
           st= con.createStatement();
           if((st.executeUpdate(query)) == 1)
           {
               //refresh jTable data
               DefaultTableModel model= (DefaultTableModel)jTable_crop.getModel();
               model.setRowCount(0);
               Show_data_in_JTable();
               
              JOptionPane.showMessageDialog(null,"Data "+message+" Successfully"); 
           }
           else
           {
               JOptionPane.showMessageDialog(null,"Data Not "+message);
           }
       }
       catch(Exception ex)
       {
           ex.printStackTrace();
       }
   }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jMenu3 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable_crop = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        serial_action_crop = new javax.swing.JTextField();
        name_action_crop = new javax.swing.JTextField();
        quantity_action_crop = new javax.swing.JTextField();
        insert_crop = new javax.swing.JButton();
        update_crop = new javax.swing.JButton();
        delete_crop = new javax.swing.JButton();
        reset_crop = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jClose = new javax.swing.JButton();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Serial", "Name", "Quantity", "Quantity Update", "Name Update", "Remove"
            }
        ));
        jTable1.setGridColor(new java.awt.Color(0, 0, 255));
        jScrollPane1.setViewportView(jTable1);

        jMenu3.setText("jMenu3");

        jMenu6.setText("jMenu6");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 2, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 255));
        jLabel1.setText("                                Crops_field");

        jPanel1.setBackground(new java.awt.Color(0, 0, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));

        jTable_crop.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Serial", "Product_Name", "Quantity"
            }
        ));
        jTable_crop.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_cropMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTable_crop);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel8.setText("Serial:");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel9.setText("Product_Name:");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel10.setText("Quantity:");

        serial_action_crop.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        name_action_crop.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        quantity_action_crop.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        insert_crop.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        insert_crop.setForeground(new java.awt.Color(0, 51, 255));
        insert_crop.setText("Insert");
        insert_crop.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        insert_crop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insert_cropActionPerformed(evt);
            }
        });

        update_crop.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        update_crop.setForeground(new java.awt.Color(0, 51, 255));
        update_crop.setText("Update");
        update_crop.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 5, true));
        update_crop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_cropActionPerformed(evt);
            }
        });

        delete_crop.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        delete_crop.setForeground(new java.awt.Color(0, 0, 255));
        delete_crop.setText("Delete");
        delete_crop.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        delete_crop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_cropActionPerformed(evt);
            }
        });

        reset_crop.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        reset_crop.setForeground(new java.awt.Color(0, 51, 255));
        reset_crop.setText("Reset");
        reset_crop.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        reset_crop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reset_cropActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(insert_crop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(delete_crop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(60, 60, 60)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(serial_action_crop)
                    .addComponent(name_action_crop)
                    .addComponent(quantity_action_crop, javax.swing.GroupLayout.DEFAULT_SIZE, 241, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(reset_crop, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(update_crop, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 587, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 454, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                    .addComponent(serial_action_crop))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(name_action_crop, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(quantity_action_crop, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(insert_crop, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(update_crop, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(delete_crop, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(reset_crop, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 0, 51));
        jButton1.setText("Back");
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jClose.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jClose.setForeground(new java.awt.Color(204, 0, 51));
        jClose.setText("Close");
        jClose.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCloseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jClose, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 193, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 733, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jClose, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.hide();
        Elements from= new Elements();
        from.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCloseActionPerformed
        // TODO add your handling code here:
        int response= JOptionPane.showConfirmDialog(this, "Are you sure to leave me?","Thinking...",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
         if(response==JOptionPane.YES_OPTION)
         {
            System.exit(0);
         }
         else
         {
            Crops No= new Crops();
            No.setVisible(true);
            No.pack();
            No.setLocationRelativeTo(null);
            No.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            setVisible(false);
         }
    }//GEN-LAST:event_jCloseActionPerformed

    private void insert_cropActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insert_cropActionPerformed
        // TODO add your handling code here:
        String query= "INSERT INTO `crops`(`Product_Name`, `Quantity`) VALUES ('"+name_action_crop.getText()+"',"+quantity_action_crop.getText()+")";       
        executeSQLQuery(query, "Inserted");
    }//GEN-LAST:event_insert_cropActionPerformed

    private void update_cropActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_cropActionPerformed
        // TODO add your handling code here:
        String query= "UPDATE `crops` SET `Product_Name`='"+name_action_crop.getText()+"',`Quantity`="+quantity_action_crop.getText()+" WHERE `Serial`="+serial_action_crop.getText();
        executeSQLQuery(query, "Updated");
    }//GEN-LAST:event_update_cropActionPerformed

    private void delete_cropActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_cropActionPerformed
        // TODO add your handling code here:
         String query= "DELETE FROM `crops` WHERE `Serial`= "+serial_action_crop.getText();
        executeSQLQuery(query, "Deleted");
    }//GEN-LAST:event_delete_cropActionPerformed

    private void jTable_cropMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_cropMouseClicked
        // TODO add your handling code here:
         //displays selected row in jTextFields
        int i= jTable_crop.getSelectedRow();
        TableModel model= jTable_crop.getModel();
        serial_action_crop.setText(model.getValueAt(i,0).toString());
        name_action_crop.setText(model.getValueAt(i,1).toString());
        quantity_action_crop.setText(model.getValueAt(i,2).toString());
    }//GEN-LAST:event_jTable_cropMouseClicked

    private void reset_cropActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reset_cropActionPerformed
        // TODO add your handling code here:
        serial_action_crop.setText(null);
        name_action_crop.setText(null);
        quantity_action_crop.setText(null);
        
    }//GEN-LAST:event_reset_cropActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Crops.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Crops.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Crops.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Crops.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Crops().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton delete_crop;
    private javax.swing.JButton insert_crop;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jClose;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable_crop;
    private javax.swing.JTextField name_action_crop;
    private javax.swing.JTextField quantity_action_crop;
    private javax.swing.JButton reset_crop;
    private javax.swing.JTextField serial_action_crop;
    private javax.swing.JButton update_crop;
    // End of variables declaration//GEN-END:variables
}
