/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package farm_owner;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;


/**
 *
 * @author PRO_
 */
public class Fishes extends javax.swing.JFrame {

    /**
     * Creates new form Fishes
     */
    public Fishes()
    {
        initComponents();
        Show_data_in_JTable();
    }
public Connection getConnection()
{
    Connection con;
    try
    {
        con=DriverManager.getConnection("jdbc:mysql://localhost/farm_owner", "root", "");
        return con;
    }
    catch(Exception e)
            {
                e.printStackTrace();
                return null;
            }
}
public ArrayList<Fish_main> getFish_mainList()
{
    ArrayList<Fish_main> Fish_mainList= new ArrayList<Fish_main>();
    Connection connection= getConnection();
    String query= "Select * From fishes";
    Statement st;
    ResultSet rs;
    try
    {
        st= connection.createStatement();
        rs= st.executeQuery(query);
        Fish_main fish_m;
        while(rs.next())
        {
            fish_m= new Fish_main(rs.getInt("Serial"),rs.getString("Product_Name"),rs.getString("Quantity"));
            Fish_mainList.add(fish_m);
        }
    }
    catch(Exception e)
    {
        e.printStackTrace();
    }
    return Fish_mainList;
}
//display data in JTable
   public void Show_data_in_JTable()
   {
       ArrayList<Fish_main> list= getFish_mainList();
       DefaultTableModel model= (DefaultTableModel)jTable_fish.getModel();
       Object[] row= new Object[3];
       for(int i=0;i<list.size();i++)
       {
           row[0]= list.get(i).getSerial();
           row[1]= list.get(i).getProductName();
           row[2]= list.get(i).getQuantity();
           
           model.addRow(row);  
       }
   }
   //execute the sql query
   public void executeSQLQuery(String query, String message)
   {
       Connection con= getConnection();
       Statement st;
       try
       {
           st= con.createStatement();
           if((st.executeUpdate(query)) == 1)
           {
               //refresh jTable data
               DefaultTableModel model= (DefaultTableModel)jTable_fish.getModel();
               model.setRowCount(0);
               Show_data_in_JTable();
               
              JOptionPane.showMessageDialog(null,"Data "+message+" Successfully"); 
           }
           else
           {
               JOptionPane.showMessageDialog(null,"Data Not "+message);
           }
       }
       catch(Exception ex)
       {
           ex.printStackTrace();
       }
   }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu3 = new javax.swing.JMenu();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_fish = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jSerial_fish = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jName_fish = new javax.swing.JTextField();
        jQuantity_fish = new javax.swing.JTextField();
        insert_fish = new javax.swing.JButton();
        update_fish = new javax.swing.JButton();
        delete_fish = new javax.swing.JButton();
        reset_fish = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jClose = new javax.swing.JButton();

        jMenu3.setText("jMenu3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 2, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 255));
        jLabel1.setText("                                Fishes_field");

        jPanel1.setBackground(new java.awt.Color(0, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 5));

        jTable_fish.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Serial", "Product_Name", "Quantity"
            }
        ));
        jTable_fish.setGridColor(new java.awt.Color(0, 0, 255));
        jTable_fish.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_fishMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable_fish);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel2.setText("Serial:");

        jSerial_fish.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel3.setText("Product_Name:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel4.setText("Quantity:");

        jName_fish.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jQuantity_fish.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        insert_fish.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        insert_fish.setForeground(new java.awt.Color(0, 0, 255));
        insert_fish.setText("Insert");
        insert_fish.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        insert_fish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insert_fishActionPerformed(evt);
            }
        });

        update_fish.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        update_fish.setForeground(new java.awt.Color(0, 51, 255));
        update_fish.setText("Update");
        update_fish.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        update_fish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_fishActionPerformed(evt);
            }
        });

        delete_fish.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        delete_fish.setForeground(new java.awt.Color(0, 0, 255));
        delete_fish.setText("Delete");
        delete_fish.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        delete_fish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_fishActionPerformed(evt);
            }
        });

        reset_fish.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        reset_fish.setForeground(new java.awt.Color(0, 0, 255));
        reset_fish.setText("Reset");
        reset_fish.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        reset_fish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reset_fishActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(insert_fish, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(delete_fish, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jQuantity_fish, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)
                        .addComponent(jName_fish, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(update_fish, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSerial_fish, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(reset_fish, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 611, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 440, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSerial_fish, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(43, 43, 43)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jName_fish, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jQuantity_fish, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(60, 60, 60)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(insert_fish, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(update_fish, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(39, 39, 39)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(delete_fish, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(reset_fish, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)))
                .addContainerGap())
        );

        jButton1.setText("jButton1");

        jButton2.setText("jButton2");

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 0, 51));
        jButton3.setText("Back");
        jButton3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jClose.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jClose.setForeground(new java.awt.Color(255, 0, 0));
        jClose.setText("Close");
        jClose.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCloseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jClose, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(130, 130, 130)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton3)
                            .addComponent(jClose, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(26, 26, 26)))
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(39, 39, 39))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        this.hide();
        Elements from= new Elements();
        from.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCloseActionPerformed
        // TODO add your handling code here:
        int response= JOptionPane.showConfirmDialog(this, "Are you sure to leave me?","Thinking...",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
         if(response==JOptionPane.YES_OPTION)
         {
            System.exit(0);
         }
         else
         {
            Fishes No= new Fishes();
            No.setVisible(true);
            No.pack();
            No.setLocationRelativeTo(null);
            No.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            setVisible(false);
         }
    }//GEN-LAST:event_jCloseActionPerformed

    private void jTable_fishMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_fishMouseClicked
        // TODO add your handling code here:
        //displays selected row in jTextFields
        int i= jTable_fish.getSelectedRow();
        TableModel model= jTable_fish.getModel();
        jSerial_fish.setText(model.getValueAt(i,0).toString());
        jName_fish.setText(model.getValueAt(i,1).toString());
        jQuantity_fish.setText(model.getValueAt(i,2).toString());
    }//GEN-LAST:event_jTable_fishMouseClicked

    private void insert_fishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insert_fishActionPerformed
        // TODO add your handling code here:
        String query= "INSERT INTO `fishes`(`Product_Name`, `Quantity`) VALUES ('"+jName_fish.getText()+"',"+jQuantity_fish.getText()+")";       
        executeSQLQuery(query, "Inserted");
    }//GEN-LAST:event_insert_fishActionPerformed

    private void update_fishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_fishActionPerformed
        // TODO add your handling code here:
        String query= "UPDATE `fishes` SET `Product_Name`='"+jName_fish.getText()+"',`Quantity`="+jQuantity_fish.getText()+" WHERE `Serial`="+jSerial_fish.getText();
        executeSQLQuery(query, "Updated");
    }//GEN-LAST:event_update_fishActionPerformed

    private void delete_fishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_fishActionPerformed
        // TODO add your handling code here:
        String query= "DELETE FROM `fishes` WHERE `Serial`= "+jSerial_fish.getText();
        executeSQLQuery(query, "Deleted");
    }//GEN-LAST:event_delete_fishActionPerformed

    private void reset_fishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reset_fishActionPerformed
        // TODO add your handling code here:
        jSerial_fish.setText(null);
        jName_fish.setText(null);
        jQuantity_fish.setText(null);
    }//GEN-LAST:event_reset_fishActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Fishes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Fishes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Fishes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Fishes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Fishes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton delete_fish;
    private javax.swing.JButton insert_fish;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jClose;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JTextField jName_fish;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jQuantity_fish;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jSerial_fish;
    private javax.swing.JTable jTable_fish;
    private javax.swing.JButton reset_fish;
    private javax.swing.JButton update_fish;
    // End of variables declaration//GEN-END:variables
}
